### ISSUE TITLE
Housing Shortage

### ISSUE THREAD

**Issue by Morse-codedecipher** [Coolsium/geognotes2021#1]
What is housing shortage ?

**Comment by jxmeen** [comment]
Housing shortage is a situation when there is insufficient housing to accommodate the population in an area, when the supply of houses cannot meet the demand. It also includes situations where housing is not affordable for those who need it.

**Comment by jxmeen** [comment]
answered

**Comment by Morse-codedecipher** [comment]
> What is housing shortage ?

Housing shortage is the situation where there is insufficient housing to accommodate the population in an area , when the supply of house cannot meet the demand . It also includes situation where housing is unaffordable to those who need it . Some indicators of housing shortage is presence of homeless people, and slums and squatter settlements
